kreiranje tabele
codejs2020/stefan-8 pull request #1
Opened 2020-07-17 21:27 UTC by stefanljusic10

Kod je ispravan, ali tabele ne rade. Ne znam zasto. Ako neko moze da pogleda bilo bi super.

2020-07-18 19:53 UTC, djpavle commented on src/index.html
> +  <link rel="stylesheet" href="style.css">
pretpostavljam da ne ucitava css jer ti fali /src/ u putanji

2020-07-18 20:02 UTC, djpavle approved these changes

2020-07-18 20:08 UTC, stefanljusic10 commented on src/index.html
> +  <link rel="stylesheet" href="style.css">
Ucitava on css, ali pravi problem kod <tr> tagova u drugoj funkciji.

2020-07-19 09:17 UTC, frontend-comtrade commented on src/zadaci.js
> +  document.getElementById("id_tabela1").innerHTML = html;
Vrati sa return, nemoj ovde da ispisuješ.

2020-07-19 09:18 UTC, frontend-comtrade commented on src/zadaci.js
> +  document.getElementById("id_tabela2").appendChild(tabela);
Vrati sa return.

2020-07-19 09:19 UTC, frontend-comtrade commented on src/zadaci.js
> +pozivTabele.addEventListener("click", ispis);
ako nešto pozivaš na samo jednom mestu obično promenljiva nije potrebna.
```
document.getElementById("id_unos_tabele").addEventListener("click", ispis)
```

2020-07-19 09:21 UTC, frontend-comtrade commented on src/zadaci.js
> +  let newTD;
Šta znači **new** u imenu? "tr" i "td" bi verovatno bili bolja imena

2020-07-19 09:22 UTC, frontend-comtrade commented on src/zadaci.js
> +      newTD.appendChild(newTR);
Ubacuješ tr u td. Treba obrnuto.

2020-07-19 09:24 UTC, frontend-comtrade commented on src/zadaci.js
> +      newTR = document.createElement("tr");
Ako se promenljive koristi samo u ovom bloku onda bi trebalo da stoji `let newTr =` a ono gore na početku let izbriši.
Uz to da si uradio `npm i` na početku ovde bi ti linter rekao da promeniš u const.

2020-07-19 09:26 UTC, frontend-comtrade requested changes
Od svega pomenutog najbitnije je da počneš da koristiš return u funkcijama tamo gde može.
Imena su takođe jako bitna.

2020-07-19 09:27 UTC, frontend-comtrade commented on src/index.html
> +  <input type="text" id="id_red">
Prefiksi `id_` u svim imenima id-eva su nepotrebni

2020-07-19 16:32 UTC, frontend-comtrade commented on src/zadaci.js
> +  document.getElementById('tabela2').appendChild(tabela)
Odradi i ovo sa return, pa je pozovi u ispis()

2020-07-19 16:33 UTC, frontend-comtrade commented on src/style.css
> +table, tr, td{
Kad već ne radi skloni tr odavde.

2020-07-21 10:00 UTC, closed without merging